<?xml version="1.0"?>
<package format="3">
  <name>rrc_tank_description</name>
  <version>0.1.0</version>
  <description>Simple tracked chassis model for Foxglove and ROS 2 TF.</description>
  <maintainer email="iecme@example.com">iecme</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
</package>
