const {JSDOM}=require('/home/iecme/apps/foxglove-opensource-cn/node_modules/jsdom');const assert=require('assert');
const dom=new JSDOM('<div class="algorithm-row"><select data-testid="nav2-local-algorithm"><option>hot_dwb</option></select></div><input data-testid="nav2-input-local_radius" value="0.6"><div><div id="panel"></div></div>');global.document=dom.window.document;global.window=dom.window;global.crypto=require('crypto').webcrypto;dom.window.HTMLElement.prototype.scrollIntoView=function(){};
(async()=>{const {initDshDiagnosticPanel}=await import('./panel-guidance-test.mjs');const sent=[];const ctx={panelElement:document.querySelector('#panel'),advertise:()=>{},unadvertise:()=>{},watch:()=>{},subscribe:()=>{},publish:(t,m)=>sent.push(JSON.parse(m.data))};const dispose=initDshDiagnosticPanel(ctx);assert.equal(document.querySelector('#panel').style.fontSize,'19.5px');assert.equal(dom.window.getComputedStyle(document.querySelector('.dsh-meta')).fontSize,'16.5px');
const input=document.querySelector('[data-testid="dsh-question"]'),ask=document.querySelector('[data-testid="dsh-ask"]'),answer=document.querySelector('[data-testid="dsh-answer"]');
function emit(extra){ctx.onRender({currentFrame:[{topic:'/omnifleet_t2/diagnostics/answer',message:{data:JSON.stringify({request_id:sent.at(-1).request_id,status:'complete',captured_at:1788770000,...extra})}}]},()=>{});}
input.value='排查无进展';ask.click();emit({answer:'检查底盘执行和反馈，不调整速度上限。',parameter_ids:['linear_speed'],parameter_labels:{linear_speed:'导航最大速度'}});assert.equal(answer.querySelectorAll('button').length,0);
input.value='检查膨胀半径错误';ask.click();emit({answer:'膨胀半径配置有明确错误。',parameter_ids:['local_radius'],parameter_labels:{local_radius:'局部膨胀半径'},parameter_actions:[{id:'local_radius',intent:'adjust',reason:'运行值为零且日志报告膨胀层异常'}]});const b=answer.querySelector('button');assert.equal(b.textContent,'定位：局部膨胀半径');assert(b.title.includes('运行值'));b.click();assert.equal(document.activeElement.value,'0.6');
input.value='局部膨胀半径在哪';ask.click();emit({answer:'在局部规划栏。',parameter_ids:['local_radius'],parameter_labels:{local_radius:'局部膨胀半径'},parameter_actions:[{id:'local_radius',intent:'inspect',reason:'用户明确询问该参数的位置'}]});assert.equal(answer.querySelector('button').textContent,'定位：局部膨胀半径');
input.value='先转到航向位置再启动路径';ask.click();emit({answer:'先切换到RPP，再检查两个具体参数。',parameter_ids:['local_controller_algorithm','rpp_use_rotate_to_heading','rpp_rotate_to_heading_min_angle'],parameter_labels:{local_controller_algorithm:'局部路径规划算法',rpp_use_rotate_to_heading:'启用航向对齐 · use_rotate_to_heading',rpp_rotate_to_heading_min_angle:'航向对齐角度阈值 · rotate_to_heading_min_angle'},parameter_actions:[{id:'local_controller_algorithm',intent:'inspect',reason:'需要先切换算法'},{id:'rpp_use_rotate_to_heading',intent:'inspect',reason:'控制是否先原地转向'},{id:'rpp_rotate_to_heading_min_angle',intent:'inspect',reason:'控制允许前进前的角度误差'}]});const buttons=[...answer.querySelectorAll('button')];assert.deepEqual(buttons.map(x=>x.textContent),['定位：局部路径规划算法','定位：启用航向对齐','定位：航向对齐角度阈值']);buttons[1].click();assert.equal(document.activeElement.dataset.testid,'nav2-local-algorithm');assert(document.querySelector('.dsh-meta').textContent.includes('请先在已定位的下拉框切换算法'));
const rpp=document.createElement('input');rpp.dataset.testid='nav2-input-rpp_use_rotate_to_heading';document.body.append(rpp);buttons[1].click();assert.equal(document.activeElement,rpp);dispose();console.log('PASS: specific parameter buttons render; inactive RPP points to selector first, then to the concrete field; no value edits');
})().catch(e=>{console.error(e);process.exitCode=1});
