#include "omnifleet_planner/arc_progress.hpp"
#include <cassert>
#include <iostream>
#include <fstream>
using namespace omnifleet_planner;
int main(int argc,char**argv){nav_msgs::msg::Path p;for(double x:{2.2,0.,3.,0.,2.6}){geometry_msgs::msg::PoseStamped a;a.pose.position.x=x;p.poses.push_back(a);}ArcProgress progress;progress.reset(p);double stamp=1.;for(int i=0;i<1000;++i)progress.update(2.2,0.,stamp+=.01);assert(progress.s()<.001);double total=0.;for(size_t leg=1;leg<p.poses.size();++leg){double a=p.poses[leg-1].pose.position.x,b=p.poses[leg].pose.position.x;int steps=int(std::ceil(std::abs(b-a)/.01));for(int j=1;j<=steps;++j){double x=a+(b-a)*j/steps;progress.update(x,0.,stamp+=.02);double expected=total+std::abs(x-a);assert(std::abs(progress.s()-expected)<.02);}total+=std::abs(b-a);assert(std::abs(progress.s()-total)<.02);}progress.reset(p);progress.update(0.,0.,stamp+=.02);assert(progress.s()<=.05);assert(progress.distance()>1.);
 nav_msgs::msg::Path sparse;for(const auto& xy:{std::pair<double,double>{0.,0.},{1.,0.},{1.,1.},{0.,1.}}){geometry_msgs::msg::PoseStamped v;v.pose.position.x=xy.first;v.pose.position.y=xy.second;sparse.poses.push_back(v);}progress.reset(sparse);progress.update(0.,0.,stamp+=.1);progress.update(.8,0.,stamp+=.1);progress.update(.2,1.,stamp+=.1);assert(std::abs(progress.s()-2.8)<.02);assert(progress.distance()<.02);
 if(argc>1){std::ifstream f(argv[1]);nav_msgs::msg::Path real;char kind;double x,y;while(f>>kind>>x>>y){if(kind!='P')continue;geometry_msgs::msg::PoseStamped v;v.pose.position.x=x;v.pose.position.y=y;real.poses.push_back(v);}assert(real.poses.size()>100);progress.reset(real);double expected=0.;for(size_t i=1;i<real.poses.size();++i){const auto&a=real.poses[i-1].pose.position;const auto&b=real.poses[i].pose.position;double length=std::hypot(b.x-a.x,b.y-a.y);int steps=std::max(1,int(std::ceil(length/.005)));for(int j=1;j<=steps;++j){progress.update(a.x+(b.x-a.x)*j/steps,a.y+(b.y-a.y)*j/steps,stamp+=.01);assert(std::abs(progress.s()-(expected+length*j/steps))<.03);}expected+=length;}std::cout<<"Actual route arc="<<expected<<" tracked="<<progress.s()<<" points="<<real.poses.size()<<std::endl;}
 std::cout<<"PASS repeated overlapping outbound/return legs, stationary samples, monotonic arclength, jump bounded\n";}
